---
AllCops:
  Exclude:
  - bin/**/*
  - vendor/**/*
  - dev/**/*
AlignParameters:
  Enabled: true
BlockDelimiters:
  Enabled: false
Documentation:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf
Layout/ExtraSpacing:
  Enabled: true
  Exclude:
  - Gemfile
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
MethodLength:
  Max: 60
Metrics/AbcSize:
  Max: 75
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 25
Naming/FileName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
NumericLiterals:
  MinDigits: 10
Security/YAMLLoad:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/UnlessElse:
  Enabled: false
Style/ClassVars:
  Enabled: false
